/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_acme_bindings_Bindings */

#ifndef _Included_eu_acme_bindings_Bindings
#define _Included_eu_acme_bindings_Bindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_acme_bindings_Bindings
 * Method:    cget
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_acme_bindings_Bindings_cget
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eu_acme_bindings_Bindings
 * Method:    cset
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_acme_bindings_Bindings_cset
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
