.\"Created with GNOME Manpages Editor Wizard
.\"sudo apt install gmanedit
.\"http://sourceforge.net/projects/gmanedit2
.TH helloworld 1 "April 11, 2021" "" "Hello World"

.SH NAME
helloworld \- library-dependant helloworld application.

.SH SYNOPSIS
.B helloworld
.RI [ options ]
.br

.SH DESCRIPTION
This manual page explains the
.B helloworld
program. This program is just a library-dependant helloworld application.
.PP
\fBhelloworld\fP is library-dependant helloworld application.

.SH OPTIONS
.B
.IP -moon
Produces a "Hello, Moon!" option, but it is still not available.

.SH "EXIT STATUS"

0 Everything hunky dory.

1 Oops.

.SH NOTES

Although this is just an example, it is functional.

.SH EXAMPLE

$ helloworld

Hello, World!

.SH "SEE ALSO"

bye-bye (never commited).

