variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - CONAN_PASSWORD="${CI_JOB_TOKEN}" conan user rodolfoap -r rodolfoap -p
        - mkdir build
        - cd build
        - cmake -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=release ..
        - make -j$(nproc)

#build_conan:
#    stage: build
#    tags: [rodolfoap]
#    except: [dev,master]
#    except:
#        variables:
#            - $DO_RELEASE
#    script:
#        - CONAN_PASSWORD="${CI_JOB_TOKEN}" conan user rodolfoap -r rodolfoap -p
#        - conan create . rodolfoap+main+libs+mylib/stable --build missing
#
#deploy_conan:
#    stage: deploy
#    tags: [rodolfoap]
#    only: [dev,master]
#    except:
#        variables:
#            - $DO_RELEASE
#    script:
#        - CONAN_PASSWORD="${CI_JOB_TOKEN}" conan user rodolfoap -r rodolfoap -p
#        - conan create . rodolfoap+main+libs+mylib/stable --build missing
#        - . VERSION
#        - conan upload mylib/${VERSION}@rodolfoap+main+libs+mylib/stable --all -r rodolfoap
